name: Build Linux

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Libraries
        run: |
          sudo apt update
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev

      - name: Run CMake
        run: cmake -G "Ninja" .

      - name: Make
        run: ninja
