name: Build Web

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          actions-cache-folder: "emsdk-cache"

      - name: Run CMake
        run: emcmake cmake -G "Unix Makefiles" . -DCMAKE_BUILD_TYPE=Release

      - name: Make
        run: make -j4
