name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Libraries
      run: |
        Set-Item -Path Env:Path -Value ("C:/msys64/usr/bin;" + $Env:Path)
        pacman --noconfirm -S mingw-w64-i686-gcc-libs mingw-w64-i686-dumb mingw-w64-i686-flac mingw-w64-i686-opusfile mingw-w64-i686-freetype mingw-w64-i686-libjpeg-turbo mingw-w64-i686-libpng mingw-w64-i686-libvorbis mingw-w64-i686-libwebp mingw-w64-i686-openal mingw-w64-i686-physfs mingw-w64-i686-allegro
      
    - name: Run CMake
      run: |
        Set-Item -Path Env:Path -Value ("C:/msys64/mingw32/bin;" + $Env:Path)
        cmake -G "MSYS Makefiles" .
      
    - name: Make
      run: |
        Set-Item -Path Env:Path -Value ("C:/msys64/mingw32/bin;" + $Env:Path)
        make 
