name: Build Mac OS

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Mac OS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Libraries
        run: |
          brew install sdl2 sdl2_image sdl2_gfx sdl2_ttf sdl2_mixer

      - name: Run CMake
        run: cmake -G "Ninja" .

      - name: Make
        run: |
          export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/local/include"
          ninja
