name: Build Windows

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Libraries
        run: |
          Set-Item -Path Env:Path -Value ("C:/msys64/usr/bin;" + $Env:Path)
          pacman --noconfirm -S mingw-w64-i686-gcc-libs mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_mixer mingw-w64-i686-SDL2_image mingw-w64-i686-SDL2_ttf mingw-w64-i686-SDL2_gfx

      - name: Run CMake
        run: |
          Set-Item -Path Env:Path -Value ("C:/msys64/mingw32/bin;" + $Env:Path)
          cmake -G "MSYS Makefiles" .

      - name: Make
        run: |
          Set-Item -Path Env:Path -Value ("C:/msys64/mingw32/bin;" + $Env:Path)
          make
