name: Build Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Mac OS
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Libraries
      run: |
        brew install allegro
        
    - name: Run CMake
      run: cmake -G "Unix Makefiles" .
    
    - name: Make
      run: |
        export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/local/include"
        make
