name: Build Windows

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            git
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_gfx
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run CMake
        run: cmake -G Ninja . -DCMAKE_BUILD_TYPE=Release

      - name: Make
        run: make -j4
