name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install graphviz
        run: sudo apt install graphviz

      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: "./Doxyfile"

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          actions-cache-folder: "emsdk-cache"

      - name: Run CMake
        run: emcmake cmake -G "Unix Makefiles" .

      - name: Make
        run: emmake make

      - name: Copy Docs to Bin
        run: cp -r ./bin/* ./docs/examples

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./docs
          force_orphan: true
